### ISSUE TITLE
Does it require a pmpro plus membership?

### ISSUE THREAD

**Issue by bulainmo** [strangerstudios/pmpro-user-pages#16]
Hi, Strangerstudios:

This seems like a good function, but it's not working on my site.
I did download it at here, so I'm not sure.
Does it require a plus membership for activation?
Then it will work fine as I expect?

**Comment by brittneyzellner** [comment]
I have also downloaded it. I created a page called "member pages" and "user pages" because the instructions are not clear but there is no where where the "user pages" settings are. When you click on "user pages" in the memberships menu it just brings me to my 404 page. Any one figure this out?

**Comment by ideadude** [comment]
None of our plugins require a license key for activation. The license key gives you access to automatic updates from our servers. Without a valid key, you will have to manually update some plugins, including this one.
