### ISSUE TITLE
Cannot activate User Pages if Unlock Add On is already activated 

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/pmpro-user-pages#21]
**Describe the bug**
If Unlock Add On is already activated, you cannot activate User Pages.

**To Reproduce**
1. Unlock Add On is already activated
2. Cannot activate User Pages

**Screenshots**
![image](https://user-images.githubusercontent.com/4752949/232113765-973e71b7-aa12-4f53-92d4-6f555f3987b5.png)

Customer sees this error upon activation:
`Fatal error: Cannot redeclare pmproup_plugin_row_meta() (previously declared in /srv/htdocs/wp-content/plugins/pmpro-unlock/includes/admin.php:63) in /srv/htdocs/wp-content/plugins/pmpro-user-pages/pmpro-user-pages.php on line 316`

I see this in the error log.

**Expected behavior**
You should be able to activate both.
**Isolating the problem:**
- [x] Deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] Reproduce this bug consistently using the steps above.

This came up in ticket 485313, and I could replicate.

**WordPress Environment**
<details> 
Paid Memberships Pro 2.10.3, User Pages Add On .6, WordPress 6.2, PHP 7.4.30
</details>

**Comment by dparker1005** [comment]
Closing as we plan to handle this issue in the PMPro Unlock Protocol Add On in the future: https://github.com/strangerstudios/pmpro-unlock/issues/12
